export const templatePresets = {
  'Ankara Boutique': [
    { type: 'Hero Banner', data: { title: 'Zara Ankara Boutique', subtitle: 'Premium Ankara Fashion · Lagos, Nigeria', bgColor: '#8B4513', btnText: 'Shop Now', image: null } },
    { type: 'Photo Gallery', data: { title: 'Our Collection', images: [null, null, null, null], bgColor: '#1C1C21' } },
    { type: 'Pricing Table', data: { title: 'Pricing', plans: [{ name: 'Casual Wear', price: 8000 }, { name: 'Occasion Wear', price: 15000 }, { name: 'Custom Design', price: 25000 }], bgColor: '#161616' } },
    { type: 'WhatsApp CTA', data: { text: '💬 Order on WhatsApp', bgColor: '#1C1C21' } },
    { type: 'Paystack Button', data: { text: '💳 Pay Online', bgColor: '#161616' } },
    { type: 'Footer', data: { text: '© 2026 Zara Ankara Boutique. All rights reserved.', bgColor: '#0a0a0a' } },
  ],
  'Suya Spot': [
    { type: 'Hero Banner', data: { title: 'Mama Titi Suya Spot', subtitle: 'The best suya in Abuja · Open daily 4PM-12AM', bgColor: '#B8860B', btnText: 'View Menu', image: null } },
    { type: 'Services', data: { title: 'Our Menu', items: [{ name: 'Beef Suya', color: '#8B4513' }, { name: 'Chicken Suya', color: '#B8860B' }, { name: 'Kilishi', color: '#3a1a1a' }], bgColor: '#1C1C21' } },
    { type: 'About Section', data: { title: 'Our Story', body: 'Family recipe passed down for three generations. Fresh grilled suya, made daily with love.', bgColor: '#161616' } },
    { type: 'WhatsApp CTA', data: { text: '💬 Order for Delivery', bgColor: '#1C1C21' } },
    { type: 'Footer', data: { text: '© 2026 Mama Titi Suya Spot.', bgColor: '#0a0a0a' } },
  ],
  'Lagos Church': [
    { type: 'Hero Banner', data: { title: 'Grace Assembly Church', subtitle: 'Sunday Service 9AM & 11AM · Abuja, Nigeria', bgColor: '#2F4F4F', btnText: 'Plan Your Visit', image: null } },
    { type: 'About Section', data: { title: 'Welcome Home', body: 'A community of faith, love, and purpose. Join us as we grow together in Christ.', bgColor: '#161616' } },
    { type: 'Team Section', data: { title: 'Our Leadership', members: [{ name: 'Pastor Emeka', photo: null }, { name: 'Pastor Grace', photo: null }] }, bgColor: '#1C1C21' },
    { type: 'Paystack Button', data: { text: '💳 Give Online', bgColor: '#161616' } },
    { type: 'FAQ Accordion', data: { title: 'FAQs', questions: [{ q: 'What time is service?', a: 'Sundays at 9AM and 11AM.' }] }, bgColor: '#1C1C21' },
    { type: 'Footer', data: { text: '© 2026 Grace Assembly Church.', bgColor: '#0a0a0a' } },
  ],
  'Abuja Clinic': [
    { type: 'Hero Banner', data: { title: 'Dr. Mensah Clinic', subtitle: 'Compassionate Healthcare · Accra, Ghana', bgColor: '#1a3a5c', btnText: 'Book Appointment', image: null } },
    { type: 'Services', data: { title: 'Our Services', items: [{ name: 'General Checkup', color: '#1a3a5c' }, { name: 'Pediatrics', color: '#2F4F4F' }, { name: 'Lab Tests', color: '#1a1a3a' }] }, bgColor: '#1C1C21' },
    { type: 'Contact Form', data: { title: 'Book Your Visit', bgColor: '#161616' } },
    { type: 'WhatsApp CTA', data: { text: '💬 Chat with Reception', bgColor: '#1C1C21' } },
    { type: 'Footer', data: { text: '© 2026 Dr. Mensah Clinic.', bgColor: '#0a0a0a' } },
  ],
  'Freelancer Portfolio': [
    { type: 'Hero Banner', data: { title: 'Kofi Design Studio', subtitle: 'Brand & Web Design · Accra, Ghana', bgColor: '#1a1a3a', btnText: 'View My Work', image: null } },
    { type: 'About Section', data: { title: 'About Me', body: 'I help African businesses build memorable brands. 5+ years of design experience.', bgColor: '#161616' } },
    { type: 'Photo Gallery', data: { title: 'Selected Work', images: [null, null, null, null] }, bgColor: '#1C1C21' },
    { type: 'Contact Form', data: { title: "Let's Work Together", bgColor: '#161616' } },
    { type: 'Footer', data: { text: '© 2026 Kofi Design Studio.', bgColor: '#0a0a0a' } },
  ],
  'Event Planning': [
    { type: 'Hero Banner', data: { title: 'Royal Event Planners', subtitle: 'Weddings · Corporate · Parties · Enugu, Nigeria', bgColor: '#3a1a3a', btnText: 'Get a Quote', image: null } },
    { type: 'Photo Gallery', data: { title: 'Past Events', images: [null, null, null, null] }, bgColor: '#1C1C21' },
    { type: 'Pricing Table', data: { title: 'Packages', plans: [{ name: 'Basic', price: 150000 }, { name: 'Premium', price: 350000 }, { name: 'Luxury', price: 600000 }] }, bgColor: '#161616' },
    { type: 'Paystack Button', data: { text: '💳 Reserve Your Date', bgColor: '#1C1C21' } },
    { type: 'Footer', data: { text: '© 2026 Royal Event Planners.', bgColor: '#0a0a0a' } },
  ],
  'Logistics Company': [
    { type: 'Hero Banner', data: { title: 'SwiftMove Logistics', subtitle: 'Fast & Reliable Delivery · Port Harcourt, Nigeria', bgColor: '#1a3a1a', btnText: 'Track Shipment', image: null } },
    { type: 'Services', data: { title: 'Our Services', items: [{ name: 'Same-Day Delivery', color: '#1a3a1a' }, { name: 'Interstate Shipping', color: '#2F4F4F' }, { name: 'Warehousing', color: '#1a1a3a' }] }, bgColor: '#1C1C21' },
    { type: 'Pricing Table', data: { title: 'Rates', plans: [{ name: 'Local', price: 2000 }, { name: 'Interstate', price: 8000 }, { name: 'Express', price: 15000 }] }, bgColor: '#161616' },
    { type: 'WhatsApp CTA', data: { text: '💬 Book a Pickup', bgColor: '#1C1C21' } },
    { type: 'Footer', data: { text: '© 2026 SwiftMove Logistics.', bgColor: '#0a0a0a' } },
  ],
  'Private School': [
    { type: 'Hero Banner', data: { title: 'Luminary Academy', subtitle: 'Excellence in Education · Kano, Nigeria', bgColor: '#1a2a3a', btnText: 'Apply Now', image: null } },
    { type: 'About Section', data: { title: 'Our Mission', body: 'Nurturing curious minds and building tomorrow\'s leaders since 2010.', bgColor: '#161616' } },
    { type: 'Team Section', data: { title: 'Our Staff', members: [{ name: 'Mrs. Adeyemi, Principal', photo: null }] }, bgColor: '#1C1C21' },
    { type: 'Contact Form', data: { title: 'Schedule a Visit', bgColor: '#161616' } },
    { type: 'Footer', data: { text: '© 2026 Luminary Academy.', bgColor: '#0a0a0a' } },
  ],
  'Beauty Salon': [
    { type: 'Hero Banner', data: { title: 'Glow Beauty Studio', subtitle: 'Hair · Makeup · Skincare · Abuja, Nigeria', bgColor: '#3a1a2a', btnText: 'Book Now', image: null } },
    { type: 'Pricing Table', data: { title: 'Our Services', plans: [{ name: 'Hair Styling', price: 5000 }, { name: 'Makeup', price: 10000 }, { name: 'Full Glam', price: 18000 }] }, bgColor: '#161616' },
    { type: 'Photo Gallery', data: { title: 'Before & After', images: [null, null, null, null] }, bgColor: '#1C1C21' },
    { type: 'WhatsApp CTA', data: { text: '💬 Book Your Slot', bgColor: '#161616' } },
    { type: 'Footer', data: { text: '© 2026 Glow Beauty Studio.', bgColor: '#0a0a0a' } },
  ],
  'Real Estate Agency': [
    { type: 'Hero Banner', data: { title: 'Skyline Properties', subtitle: 'Find Your Dream Home · Kumasi, Ghana', bgColor: '#2a1a1a', btnText: 'Browse Listings', image: null } },
    { type: 'Photo Gallery', data: { title: 'Featured Properties', images: [null, null, null, null] }, bgColor: '#1C1C21' },
    { type: 'Contact Form', data: { title: 'Enquire Now', bgColor: '#161616' } },
    { type: 'WhatsApp CTA', data: { text: '💬 Talk to an Agent', bgColor: '#1C1C21' } },
    { type: 'Footer', data: { text: '© 2026 Skyline Properties.', bgColor: '#0a0a0a' } },
  ],
  'NGO & Charity': [
    { type: 'Hero Banner', data: { title: 'Hope Foundation', subtitle: 'Changing Lives Across Rwanda', bgColor: '#1a3a2a', btnText: 'Donate Now', image: null } },
    { type: 'About Section', data: { title: 'Our Impact', body: 'Over 5,000 families supported since 2018 through education, health, and community programs.', bgColor: '#161616' } },
    { type: 'Photo Gallery', data: { title: 'Our Projects', images: [null, null, null, null] }, bgColor: '#1C1C21' },
    { type: 'Paystack Button', data: { text: '💳 Donate via Paystack', bgColor: '#161616' } },
    { type: 'Footer', data: { text: '© 2026 Hope Foundation.', bgColor: '#0a0a0a' } },
  ],
  'Tech Startup': [
    { type: 'Hero Banner', data: { title: 'TechBridge Africa', subtitle: 'Connecting African Talent to Global Tech Jobs', bgColor: '#0a0a2a', btnText: 'Join Waitlist', image: null } },
    { type: 'Services', data: { title: 'What We Offer', items: [{ name: 'Skill Training', color: '#0a0a2a' }, { name: 'Job Matching', color: '#1a1a3a' }, { name: 'Mentorship', color: '#2F4F4F' }] }, bgColor: '#1C1C21' },
    { type: 'Pricing Table', data: { title: 'Plans', plans: [{ name: 'Free', price: 0 }, { name: 'Pro', price: 5000 }, { name: 'Premium', price: 12000 }] }, bgColor: '#161616' },
    { type: 'Contact Form', data: { title: 'Get Started', bgColor: '#1C1C21' } },
    { type: 'Footer', data: { text: '© 2026 TechBridge Africa.', bgColor: '#0a0a0a' } },
  ],
}

export const templatePrices = {
  'Ankara Boutique': 11,
  'Suya Spot': 10,
  'Lagos Church': 19,
  'Abuja Clinic': 15,
  'Freelancer Portfolio': 9,
  'Event Planning': 11,
  'Logistics Company': 18,
  'Private School': 18,
  'Beauty Salon': 9,
  'Real Estate Agency': 21,
  'NGO & Charity': 14,
  'Tech Startup': 22,
}
